port:  5000
markdown: kramdown
name: "Bluest Lie"
url: http://byp100.github.io/bluest-lie
encoding: utf-8
timezone: America/Chicago
description: "Join the campaign to fight the 'Blue Lives Matter' ordinance!"
gems:
  - jekyll-redirect-from
